import './globals.css'
import { ReactNode } from 'react'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
import WrapProvider from '@/components/WrapProvider'

export const metadata = {
  title: 'Meta spark',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <WrapProvider>

        
          {children}
        </WrapProvider>
        
      </body>
    </html>
  )
}
